config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'sales/index'
  end
  devise_for :admins
 
  root to: 'admins_backoffice/welcome#index'
  
  namespace :admins_backoffice do
   get 'welcome/index'
   resources :clients
   resources :products
   resources :sales
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :sales
    
    validates :name, presence: true
    validates :email, presence: true,
                      uniqueness: true
    validates :birthdate, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :sale
    belongs_to :product

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orders
    has_many :sales, through: :orders
    
    validates :name, presence: true,
                     uniqueness: true
    validates :description, presence: true
    validates :price_cents, presence: true,
                            numericality: { only_integer: true,
                                            greater_than_or_equal_to: 0 }
    
    def price
        price_cents.to_f / 100.0
    end
end

app/models/sale.rb
class Sale < ApplicationRecord

    belongs_to :client
    has_many :orders
    has_many :products, through: :orders
end

app/controllers/admins_backoffice/clients_controller.rb
class AdminsBackoffice::ClientsController < AdminsBackofficeController
	before_action :set_client, only: [:show, :edit, :update, :destroy]

	def index
		@clients = Client.all
	end

	def show
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)

		if @client.save
			flash[:notice] = 'Client was created successfully!'
			redirect_to admins_backoffice_clients_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @client.update(client_params)
			flash[:notice] = 'Client was updated successfully!'
			redirect_to admins_backoffice_client_path(@client)
		else
			render 'edit'
		end
	end

	def destroy
		@client.destroy
		redirect_to admins_backoffice_clients_path
	end

	private

	def set_client
		@client = Client.find(params[:id])
	end

	def client_params
		params.require(:client).permit(:name, :email, :birthdate)
	end
end

app/controllers/admins_backoffice/products_controller.rb
class AdminsBackoffice::ProductsController < AdminsBackofficeController
	before_action :set_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def show
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)

		if @product.save
			flash[:notice] = 'Product was created successfully!'
			redirect_to admins_backoffice_products_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @product.update(product_params)
			flash[:notice] = 'Product was updated successfully!'
			redirect_to admins_backoffice_product_path(@product)
		else
			render 'edit'
		end
	end

	def destroy
		@product.destroy
		redirect_to admins_backoffice_products_path
	end

	private

	def set_product
		@product = Product.find(params[:id])
	end

	def product_params
		params.require(:product).permit(:name, :description, :price_cents)
	end
end

app/controllers/admins_backoffice/sales_controller.rb
class AdminsBackoffice::SalesController < AdminsBackofficeController
	before_action :set_sale, only: [:show, :edit, :update, :destroy]

	def index
		@sales = Sale.all
	end

	def show
	end

	def new
		@sale = Sale.new
	end

	def create
		@client = Client.find(sale_params[:client_id])
		@sale = @client.sales.build
		sale_params[:product_ids].each do |product_id| 
			
			unless product_id.empty?
				@product = Product.find(product_id.to_i)
				@sale.products << @product
			end
		end

		
		if @sale.save
			flash[:notice] = 'Sale was created successfully!'
			redirect_to admins_backoffice_sales_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @sale.update(sale_params)
			flash[:notice] = 'Sale was updated successfully!'
			redirect_to admins_backoffice_sale_path(@sale)
		else
			render 'edit'
		end
	end

	def destroy
		@sale.destroy
		redirect_to admins_backoffice_sales_path
	end

	private

	def set_sale
		@sale = Sale.find(params[:id])
	end

	def sale_params
		params.require(:sale).permit(:client_id, :product_ids =>[])
	end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admins_backoffice/clients_helper.rb
module AdminsBackoffice::ClientsHelper
end

app/helpers/admins_backoffice/product_helper.rb
module AdminsBackoffice::ProductHelper
end

app/helpers/admins_backoffice/sales_helper.rb
module AdminsBackoffice::SalesHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins_backoffice/clients/_form.html.erb
<% if @client.errors.any? %>
	<h2>The following errors prevented the client from being saved:</h2>
	<ul>
		<% @client.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
<%= form_with(model: [:admins_backoffice, @client], local: true) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_area :email %>
	</p>
	
	<p>
		<%= f.label :birthdate %><br>
		<%= f.date_field :birthdate %>
	</p>
	
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/admins_backoffice/clients/edit.html.erb
<h1>Edit client</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Return to Clients listing', admins_backoffice_clients_path %>
</p>

app/views/admins_backoffice/clients/index.html.erb
<h1>Clients listing page</h1>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Birthdate</th>
			<th colspan="3">Action</th>
		</tr>
	</thead>
	<tbody>
		<% @clients.each do |client| %>
    	<tr>
    		<td><%= client.name %></td>
    		<td><%= client.email %></td>
    		<td><%= client.birthdate %></td>
    		<td><%= link_to 'Show', admins_backoffice_client_path(client) %></td>
    		<td><%= link_to 'Edit', edit_admins_backoffice_client_path(client) %></td>
    		<td><%= link_to 'Delete', admins_backoffice_client_path(client), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    	</tr>
		<% end %>
	</tbody>
</table>
<p>
	<%= link_to 'Home page', root_path %> |
	<%= link_to 'Create new client', new_admins_backoffice_client_path %>
</p>

app/views/admins_backoffice/clients/new.html.erb
<h1>Create new Client</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Return to Client listing', admins_backoffice_clients_path %>
</p>

app/views/admins_backoffice/clients/show.html.erb
<h1>Showing client details</h1>

<p><strong>Name: </strong><%= @client.name %></p>
<p><strong>Email: </strong><%= @client.email %></p>
<p><strong>Birthdate: </strong><%= @client.birthdate %></p>

<p>
	<%= link_to 'Edit', edit_admins_backoffice_client_path(@client) %> |
	<%= link_to 'Delete', admins_backoffice_client_path(@client), method: :delete, data: { confirm: 'Are you sure?' }%> |
	<%= link_to 'Return to clients listing', admins_backoffice_clients_path %>
</p>

app/views/admins_backoffice/products/_form.html.erb
<% if @product.errors.any? %>
	<h2>The following errors prevented the product from being saved:</h2>
	<ul>
		<% @product.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
<%= form_with(model: [:admins_backoffice, @product], local: true) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	
	<p>
		<%= f.label 'Price (Cents)' %><br>
		<%= f.text_area :price_cents %>
	</p>
	
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/admins_backoffice/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Return to Product listing', admins_backoffice_products_path %>
</p>

app/views/admins_backoffice/products/index.html.erb
<h1>Products listing page</h1>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Price</th>
			<th colspan="3">Action</th>
		</tr>
	</thead>
	<tbody>
		<% @products.each do |product| %>
    	<tr>
    		<td><%= product.name %></td>
    		<td><%= product.description %></td>
    		<td><%= product.price %></td>
    		<td><%= link_to 'Show', admins_backoffice_product_path(product) %></td>
    		<td><%= link_to 'Edit', edit_admins_backoffice_product_path(product) %></td>
    		<td><%= link_to 'Delete', admins_backoffice_product_path(product), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    	</tr>
		<% end %>
	</tbody>
</table>
<p>
	<%= link_to 'Home page', root_path %> |
	<%= link_to 'Create new product', new_admins_backoffice_product_path %>
</p>

app/views/admins_backoffice/products/new.html.erb
<h1>Create new Product</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Return to Product listing', admins_backoffice_products_path %>
</p>

app/views/admins_backoffice/products/show.html.erb
<h1>Showing Product details</h1>

<p><strong>Name: </strong><%= @product.name %></p>
<p><strong>Description: </strong><%= @product.description %></p>
<p><strong>Price: </strong><%= @product.price %></p>

<p>
	<%= link_to 'Edit', edit_admins_backoffice_product_path(@product) %> |
	<%= link_to 'Delete', admins_backoffice_product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }%> |
	<%= link_to 'Return to products listing', admins_backoffice_products_path %>
</p>

app/views/admins_backoffice/sales/_form.html.erb
<% if @sale.errors.any? %>
	<h2>The following errors prevented the sale from being saved:</h2>
	<ul>
		<% @sale.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>
<%= form_with(model: [:admins_backoffice, @sale], local: true) do |f| %>
	<p>
		<%= f.label :client_id %><br>
		<%= f.collection_select :client_id, Client.all, :id, :name %>
	</p>
	<p>
		<%= f.label :product_id %><br>
		<% klass = f.object.class.model_name.param_key %>
		<%= f.collection_select :product_ids, Product.all, :id, :name, {:include_blank => true}, {:multiple => true} %>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
	
	


<% end %>

app/views/admins_backoffice/sales/edit.html.erb
<h1>Edit Sale</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Return to Sale listing', admins_backoffice_sales_path %>
</p>

app/views/admins_backoffice/sales/index.html.erb
<h1>Sales listing page</h1>

<table>
	<thead>
		<tr>
			<th>#</th>
			<th>Sales</th>
			<th colspan="3">Action</th>
		</tr>
	</thead>
	<tbody>
		<% @sales.each do |sale| %>
    	<tr>
    		<td><%= sale.id %></td>
    		<td><%= sale.client.name %></td>
    		<td><%= link_to 'Show', admins_backoffice_sale_path(sale) %></td>
    		<td><%= link_to 'Edit', edit_admins_backoffice_sale_path(sale) %></td>
    		<td><%= link_to 'Delete', admins_backoffice_sale_path(sale), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    	</tr>
		<% end %>
	</tbody>
</table>
<p>
	<%= link_to 'Home page', root_path %> |
	<%= link_to 'Create new sale', new_admins_backoffice_sale_path %>
</p>

app/views/admins_backoffice/sales/new.html.erb
<h1>Create new Product</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Return to Product listing', admins_backoffice_products_path %>
</p>

app/views/admins_backoffice/sales/show.html.erb
<h1>Showing Sale details</h1>

<p><strong>ID: </strong><%= @sale.id %></p>
<p><strong>Client: </strong><%= @sale.client.name %></p>
<p><strong>Products: </strong>
	<ul>
		<%= @sale.products.each do |product| %>
			<li><%= product.name %></li>
		<% end %>
	</ul>
</p>

<p>
	<%= link_to 'Edit', edit_admins_backoffice_sale_path(@sale) %> |
	<%= link_to 'Delete', admins_backoffice_sale_path(@sale), method: :delete, data: { confirm: 'Are you sure?' }%> |
	<%= link_to 'Return to sales listing', admins_backoffice_sales_path %>
</p>

app/views/layouts/admins_backoffice.html.erb
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin 2 - Blank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application' %>    
    <%= stylesheet_link_tag    'admins_backoffice' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
</head>
<body id="page-top">
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                </div>
                <div class="sidebar-brand-text mx-3">NowGo <sup>42</sup></div>
            </a>
            <hr class="sidebar-divider my-0">
            <li class="nav-item">
                <a class="nav-link" href="<%= admins_backoffice_welcome_index_path %>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Home</span></a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" href="<%= admins_backoffice_clients_path %>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Clients</span></a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" href="<%= admins_backoffice_products_path %>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Products</span></a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" href="<%= admins_backoffice_sales_path %>">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Sales</span></a>
            </li>
            <hr class="sidebar-divider">
        </ul>
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown no-arrow mx-1">
                        </li>
                        <a class="btn btn-primary btn-custom">
                            Profile
                        </a>
                        <div class="topbar-divider d-none d-sm-block"></div>
                        <a class="btn btn-primary btn-custom">
                            Logout
                        </a>
                    </ul>
                </nav>
                <div class="container-fluid"
                    <%= yield %>
                </div>
            </div>
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Que a força esteja com todos nós em tempos sombrios como esses.</span>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'admins_backoffice' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NowGo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>